# Generated by Django 6.0.4 on 2026-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('UL', 'Unpaid Leave'), ('EL', 'Earned Leave')], default='CL', max_length=5),
        ),
    ]
