# Generated by Django 6.0.4 on 2026-04-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('UL', 'Unplanned Leave'), ('EL', 'Earned Leave')], default='CL', max_length=5),
        ),
        migrations.AlterField(
            model_name='roster',
            name='shift_code',
            field=models.CharField(choices=[('E', 'E'), ('E-2', 'E-2'), ('M', 'M'), ('A', 'A'), ('N', 'N'), ('CL', 'CL'), ('EL', 'EL'), ('UL', 'UL'), ('H', 'H'), ('ML', 'ML'), ('HY', 'HY'), ('WO', 'WO')], max_length=10),
        ),
    ]
